apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollingupdate
  namespace: argocd
spec:
  project: default
  source:
    path: rollingupdate/
    repoURL: 'https://github.com/sangntRND/gitops-k8s-deployment-strategy.git'
    targetRevision: main
  destination:
    namespace: rollingupdate
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2