grafana:
  enabled: true
  adminPassword: prom-operator
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.local
  persistence:
    enabled: true
    size: 5Gi

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.local
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}

alertmanager:
  enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - alertmanager.local

prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false